name: Playwright Tests

on:
  push:
    branches: [ "main" ]       # runs when code is pushed to main branch
  pull_request:
    branches: [ "main" ]       # runs on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests with Allure
      - name: Run tests
        run: npx playwright test --reporter=list,allure-playwright

      # Step 6: Generate Allure report
      - name: Generate Allure Report
        run: npx allure generate ./allure-results --clean -o ./allure-report

      # Step 7: Upload Allure report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      # Step 8: Upload Playwright HTML report
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./playwright-report
